CREATE DATABASE mydatabase;

use mydatabase;


-- Q1. What is the total revenue generated by male vs. female customers?

select gender ,sum(purchase_amount) as revenue
from mytable
group by gender;



-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from mytable
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from mytable);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    AVG(review_rating) AS avg_rating
FROM mytable
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase
FROM mytable
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY subscription_status;



-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_filtered AS (
    SELECT 
        customer_id,
        previous_purchases,
        purchase_amount,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM mytable
    WHERE discount_applied = 'Yes'
    AND purchase_amount > (
        SELECT AVG(purchase_amount) FROM mytable
    )
)

SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer_filtered
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM mytable
    GROUP BY category, item_purchased
) ranked
WHERE rnk <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS customer_count
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;




-- Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue DESC;